CREATE TABLE "role" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" varchar UNIQUE,
                        "description" varchar
);

CREATE TABLE "parking_lot" (
                               "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "name" varchar,
                               "address" varchar,
                               "opening_time" time,
                               "closing_time" time,
                               "rows" int,
                               "columns" int,
                               "auto_assignment" boolean,
                               "discounts_enabled" boolean
);

CREATE TABLE "user" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "document" varchar UNIQUE NOT NULL,
                        "name" varchar NOT NULL,
                        "phone" varchar,
                        "username" varchar UNIQUE,
                        "password_hash" varchar NOT NULL,
                        "role_id" bigint NOT NULL,
                        "active" boolean,
                        "failed_attempts" int,
                        "blocked" boolean,
                        "parking_lot_id" bigint,
                        "created_at" timestamp
);

CREATE TABLE "vehicle_type" (
                                "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "name" varchar UNIQUE,
                                "requires_plate" boolean
);

CREATE TABLE "vehicle" (
                           "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "vehicle_type_id" bigint NOT NULL,
                           "plate" varchar UNIQUE,
                           "bike_registration" varchar UNIQUE,
                           "owner_id" bigint,
                           "brand" varchar,
                           "model" varchar,
                           "color" varchar,
                           "active" boolean
);


CREATE TABLE "cell" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "parking_lot_id" bigint NOT NULL,
                        "row" int,
                        "col" int,
                        "code" varchar,
                        "cell_type" varchar,
                        "status" varchar,
                        "vehicle_type_id" bigint,
                        "reserved_for_staff" boolean,
                        "active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rate" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "parking_lot_id" bigint NOT NULL,
                        "vehicle_type_id" bigint NOT NULL,
                        "rate_type" varchar,
                        "cost" decimal,
                        "start_date" timestamp,
                        "end_date" timestamp,
                        "active" boolean
);

CREATE TABLE "discount_config" (
                                   "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "parking_lot_id" bigint NOT NULL,
                                   "active" boolean,
                                   "min_external_invoice" decimal,
                                   "min_visits" int,
                                   "discount_percentage" decimal,
                                   "start_date" timestamp,
                                   "end_date" timestamp
);

CREATE TABLE "entry_record" (
                                "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "vehicle_id" bigint NOT NULL,
                                "cell_id" bigint NOT NULL,
                                "recorded_by" bigint,
                                "entry_time" timestamp,
                                "exit_time" timestamp,
                                "duration" int,
                                "status" varchar
);

CREATE TABLE "payment" (
                           "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "entry_record_id" bigint UNIQUE,
                           "subtotal" decimal,
                           "discount_percentage" decimal,
                           "discount_amount" decimal,
                           "total_paid" decimal,
                           "payment_method" varchar,
                           "payment_date" timestamp,
                           "external_invoice_ref" varchar
);

CREATE TABLE "invoice" (
                           "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "payment_id" bigint UNIQUE,
                           "invoice_number" varchar UNIQUE,
                           "issued_at" timestamp
);

ALTER TABLE "user" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user" ADD FOREIGN KEY ("parking_lot_id") REFERENCES "parking_lot" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicle" ADD FOREIGN KEY ("vehicle_type_id") REFERENCES "vehicle_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicle" ADD FOREIGN KEY ("owner_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cell" ADD FOREIGN KEY ("parking_lot_id") REFERENCES "parking_lot" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cell" ADD FOREIGN KEY ("vehicle_type_id") REFERENCES "vehicle_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rate" ADD FOREIGN KEY ("parking_lot_id") REFERENCES "parking_lot" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rate" ADD FOREIGN KEY ("vehicle_type_id") REFERENCES "vehicle_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discount_config" ADD FOREIGN KEY ("parking_lot_id") REFERENCES "parking_lot" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_record" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicle" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_record" ADD FOREIGN KEY ("cell_id") REFERENCES "cell" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_record" ADD FOREIGN KEY ("recorded_by") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment" ADD FOREIGN KEY ("entry_record_id") REFERENCES "entry_record" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoice" ADD FOREIGN KEY ("payment_id") REFERENCES "payment" ("id") DEFERRABLE INITIALLY IMMEDIATE;